spring:
  application.name: Eventful
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 10000
      max-lifetime: 1000
      maximum-pool-size: 5
      minimum-idle: 5
    password: r717vg38eibf6la5
    url: jdbc:mariadb://ao9moanwus0rjiex.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ng1c9d0ndmugjxfm
    username: wjaxqeu6ddcwwnsx
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    repeatable-sql-migration-prefix: R
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
weather:
  apikey: 50602764f3f29950bbdb1d46c3b0f8b5
  url: https://api.openweathermap.org/data/2.5/weather

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - io.github.robwin.exception.BusinessException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - io.github.robwin.exception.BusinessException
  instances:
    backendA:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - io.github.robwin.exception.BusinessException
  instances:
    backendA:
      baseConfig: default